services:
  sing-box: # 一般使用http://yacd.haishan.me配置
    image: ghcr.io/sagernet/sing-box
    container_name: sing-box
    restart: always
    volumes:
      - ./:/etc/sing-box/
    network_mode: host
    command: -D /var/lib/sing-box -C /etc/sing-box/ run
