services:
  # nginx代理面板 控制台端口81
  nginx:
    container_name: nginx
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./nginx:/data
      - ./letsencrypt:/etc/letsencrypt
    environment:
      - http_proxy=http://127.0.0.1:7890
      - https_proxy=http://127.0.0.1:7890
      - HTTP_PROXY=http://127.0.0.1:7890
      - HTTPS_PROXY=http://127.0.0.1:7890
      - all_proxy=http://127.0.0.1:7890
      - ALL_PROXY=http://127.0.0.1:7890
  # ddns面板 控制台端口9876
  ddns-go:
    container_name: ddns-go
    restart: always
    network_mode: host
    volumes:
      - ./ddns-go:/root
    image: jeessy/ddns-go
