services:
  # nginx代理面板 控制台端口81
  nginx:
    container_name: nginx
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./nginx:/data
      - ./letsencrypt:/etc/letsencrypt
  # environment:
     # - http_proxy=http://127.0.0.1:1080
     # - https_proxy=http://127.0.0.1:1080
     # - HTTP_PROXY=http://127.0.0.1:1080
     # - HTTPS_PROXY=http://127.0.0.1:1080
     # - all_proxy=http://127.0.0.1:1080
     # - ALL_PROXY=http://127.0.0.1:1080
  # ddns面板 控制台端口9876
  ddns-go:
    container_name: ddns-go
    restart: always
    network_mode: host
    volumes:
      - ./ddns-go:/root
    image: jeessy/ddns-go
