services:
  alist:
    image: 'xhofe/alist:latest-aio'
    container_name: alist
    volumes:
      - ./alist:/opt/alist/data
      - /srv:/srv
      - /mnt:/mnt
    ports:
      - '5244:5244'
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
      - TZ=Asia/Shanghai
      - http_proxy=http://host.docker.internal:7890
      - https_proxy=http://host.docker.internal:7890
      - HTTP_PROXY=http://host.docker.internal:7890
      - HTTPS_PROXY=http://host.docker.internal:7890
      - all_proxy=socks5://host.docker.internal:7890
      - ALL_PROXY=socks5://host.docker.internal:7890
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
  samba:
    image: dockurr/samba
    container_name: samba
    ports:
      - 445:445
    volumes:
      - ./smb.conf:/etc/samba/smb.conf # 映射文件夹主要配置
      - ./users.conf:/etc/samba/users.conf # 多用户管理
      - /srv:/srv
      - /mnt:/mnt