services:
  jelly: # 端口为8096
    image: jellyfin/jellyfin
    container_name: jelly
    network_mode: host
    volumes:
      - /srv:/srv
      - /mnt:/mnt
      - ./jelly/config:/config
      - ./jelly/cache:/cache
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - http_proxy=http://127.0.0.1:7890
      - https_proxy=http://127.0.0.1:7890
      - HTTP_PROXY=http://127.0.0.1:7890
      - HTTPS_PROXY=http://127.0.0.1:7890
      - all_proxy=socks5://127.0.0.1:7890
      - ALL_PROXY=socks5://127.0.0.1:7890
