services:
  alist:
    image: 'xhofe/alist:latest-aio'
    container_name: alist
    volumes:
      - ./alist:/opt/alist/data
    ports:
      - '5244:5244'
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=022
    restart: unless-stopped