services:
#  qbittorrent:
#    image: lscr.io/linuxserver/qbittorrent:latest
#    container_name: qbittorrent
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - TZ=Asia/Shanghai
#      - WEBUI_PORT=8080
#      - TORRENTING_PORT=6881
#      - http_proxy=http://127.0.0.1:7890
#      - https_proxy=http://127.0.0.1:7890
#      - HTTP_PROXY=http://127.0.0.1:7890
#      - HTTPS_PROXY=http://127.0.0.1:7890
#      - all_proxy=http://127.0.0.1:7890
#      - ALL_PROXY=http://127.0.0.1:7890
#    volumes:
#      - ./qbit:/config
#      - /srv:/srv
#    network_mode: host
#    restart: unless-stopped
  qbittorrentee: # 控制面板端口为8080，网络模式必须为host，方便peerbanhelper获取ip
    image: superng6/qbittorrentee
    container_name: qbittorrentee
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
      - WEB_USER=admin
      - TORRENTING_PORT=6882
      - http_proxy=http://127.0.0.1:7890
      - https_proxy=http://127.0.0.1:7890
      - HTTP_PROXY=http://127.0.0.1:7890
      - HTTPS_PROXY=http://127.0.0.1:7890
      - all_proxy=http://127.0.0.1:7890
      - ALL_PROXY=http://127.0.0.1:7890
    volumes:
      - ./qbitee:/config
      - /srv:/srv
    network_mode: host
    restart: unless-stopped
  peerbanhelper: # 控制面板端口9898
    image: "ghostchu/peerbanhelper:v7.4.3"
    restart: unless-stopped
    container_name: "peerbanhelper"
    volumes:
      - ./pbh:/app/data
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - http_proxy=http://127.0.0.1:7890
      - https_proxy=http://127.0.0.1:7890
      - HTTP_PROXY=http://127.0.0.1:7890
      - HTTPS_PROXY=http://127.0.0.1:7890
      - all_proxy=http://127.0.0.1:7890
      - ALL_PROXY=http://127.0.0.1:7890
